#start
print('             ')
print('S C O R P I O N H E A D by Bryana Dawkins')
print('             ')
print('"O, full of scorpions is my mind, dear wife!" -Shakespeare, William. "Macbeth." 3.2.36-45')
print('             ')
v1 = input('PRESS ENTER TO START')
print('             ')
print('INPUT PROCESSING...')
import time
time.sleep(2)

#part 1
print('             ')
print('Puzzleman in the doorway. Anarchist, Dakota red. Yin ‘n’ anima[l]: vessels [of blood].')
time.sleep(1)
print('Pustules, yes? Her latent masculinity. Declining')
time.sleep(1)
print('                                                 viewership. Interoceptors, [de]coded.')
time.sleep(1)
print('Sleep, indefinite.     			             	               	     [eroded].')
time.sleep(1)
print('She shifts radio frequencies.		                               [desensitized].')
time.sleep(1)
print('             ')

#part 2
print('Why?')
print('             ')
v2 = input('(PLEASE TYPE IN YOUR ANSWER)')
print('             ')
print('INPUT PROCESSING...')
time.sleep(2)
print('             ')
print(v2,'?')
time.sleep(2)
print('             ')
print('INCORRECT')
print('             ')
time.sleep(1)
print('Because:')
time.sleep(1)
print('1. She is fond of him [raptured]                                [she lives perfectly].')
time.sleep(1)
print('2. Raptured [she is fond of him]                                   [adores endlessly].')
time.sleep(1)
print('3. She is being very honest                                        [she, white doves].')
time.sleep(1)
print('4. She is not fond of men                                        [adores unceasingly].')
time.sleep(1)
print('5. She is not fond of anyone                                                [but him].')
time.sleep(1)
print('6. No switch is flipped     [she only recognizes her own hand when holding another’s].')
time.sleep(1)
print('7. Asexual [no]body                                                [she, abstraction].')
time.sleep(5)

#part 3
print('             ')
print('- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print('             ')
print('Sex[less] dark.')
time.sleep(1)
print('Deathless.')
time.sleep(1)
print('                         Sunburst electric spoke out an image of hellish machinery and')
time.sleep(1)
print('                    excess piled up in the shape of sandcastles.')
time.sleep(1)
print('                    She sentences herself to liminality.')
time.sleep(1)
print('                    How do they give themselves away so easily, she thinks [hot dick].')
time.sleep(1)
print('                                                         She loves how she’s not real.')
time.sleep(1)
print('                                 Testosterone ’n’ estrogening             [her drift].')
time.sleep(5)

#part 4
print('             ')
print('- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print('             ')
print('Space dream approximates electromagnetic spectrum itch with the twitch of her left')
time.sleep(1)
print('index finger. She is not random; she is a complicated assortment of tangled wires that')
time.sleep(1)
print('are impossible to separate as they bleed into each other like estuaries. That is a')
time.sleep(1)
print('stolen gland, a misplaced appendage, being dragged by the station wagon bodiless to')
time.sleep(1)
print('the end of being, and is it lost, the opportunity to reconcile her b[lack] mass with')
time.sleep(1)
print('the container it clings to?')
print('             ')
v3 = input('(PLEASE TYPE IN YOUR ANSWER)')
print('             ')
print('INPUT PROCESSING...')
print('             ')
time.sleep(2)
print(v3,'?')
time.sleep(2)
print('             ')
print('INCORRECT')
time.sleep(1)
print('             ')
print('Because:')
time.sleep(5)

#part 5
print('- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - ')
print('             ')
print('There are ways to speak through light but she knows none of them. The hy[men]')
time.sleep(1)
print('is a part of her meant to be broken. [She cannot speak through light]. She sinks')
time.sleep(1)
print('into ambiguity and grows ambivalent. [There is a part of her meant to be ')
time.sleep(1)
print('broken]. Dog spit heralded as jewels half-mooned like a lunula harvested like')
time.sleep(1)
print('swollen blackberries in the July sun. [There is a part of her meant to be')
time.sleep(1)
print('broken]. L[am]b, sacrificial? [The re is a p AR T of her mea nt to be Bro ke n]. THeR ')
time.sleep(1)
print('i S a pA rT o f h e r m e A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R ')
time.sleep(1)

#glitch
print('M E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R ')
time.sleep(0.75)
print('O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S ')
time.sleep(0.5)
print('A P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M ')
time.sleep(0.25)
print('E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O ')
time.sleep(0.125)
print('K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A ')
print('P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E ')
print('A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K ')
print('E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P ')
print('A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A ')
print('N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E ')
print('N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P A ')
print('R T O F H E R M E A N T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N ')
print('T T O B E B R O K E N T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N ')
print('T H E R E I S A P A R T O F H E R M E A N T T O B E B R O K E N T H E R ESYSTEM ERROR ')
time.sleep(0.125)

#crash
import os
import platform
import random
import string
def clear_screen():
    os.system('clear')
def glitch_effect(lines=100, length=85):
        for _ in range(lines):
            print(''.join(random.choices(string.ascii_letters + string.punctuation, k=length)))
            time.sleep(0.00001)
glitch_effect()
time.sleep(0.5)
clear_screen()
time.sleep(3)

#part 6 (reboot)
print('             ')
print('REBOOTING...')
time.sleep(3)
clear_screen()
time.sleep(3)
print('             ')
print('She shifts radio frequencies.		                              [desensitized].')
time.sleep(1)
print('             ')
print('Why?')
print('             ')
v4 = input('(PLEASE TYPE IN YOUR ANSWER)')
print('             ')
print('INPUT PROCESSING...')
print('             ')
time.sleep(2)
print(v4,'?')
time.sleep(2)
print('             ')
print('INCORRECT')
print('             ')
time.sleep(1)
print('Because:')
time.sleep(1)
print('1. She is fond of him [captured].')
time.sleep(1)
print('2. She is resisting the desire to delete and reset                   [penal, defunct].')
time.sleep(1)
print('3. C[lip]ped things dust and rage                   [she must grieve the air bubbles].')
time.sleep(1)
print('             ')
print('And flu[id]ity is her preferred mode of understanding.                 [intransigent].')
time.sleep(1)
print('             ')
print('INITIATING SYSTEM SHUTDOWN...')
print('             ')
import sys
time.sleep(1)
sys.exit()






